version: "3"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=okto
      - MYSQL_DATABASE=okto
    ports:
      - 3306:3306
  okto:
    image: krosf/iw:latest
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    ports:
      - 8080:8080
    links:
      - mysql
    depends_on:
      - mysql
